---
# - name: Ensure pipx environment variables in ~/.zshrc
#   ansible.builtin.lineinfile:
#     dest: '~/.zshrc'
#     regexp: '^export PATH=$PATH:$HOME/.local/bin'
#     line: 'export PATH=$PATH:$HOME/.local/bin'
#     state: present
#   become: false

- name: Installing pipx-tools (from pypi)
  community.general.pipx:
    executable: "/usr/bin/pipx"
    name: "{{ item }}"
    state: present
  loop:
    - impacket
    - arjun
    - uro
    - dnschef-ng
    - certipy-ad
    - poetry
    - bloodyad
    - git-dumper
    - remotezip
    - dnsgen
  environment: 
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  register: pipx_result

- name: Installing pipx-tools (from github)
  community.general.pipx:
    executable: "/usr/bin/pipx"
    name: "{{ item.name }}"
    source: "{{ item.source }}"
    state: install
  retries: 3
  delay: 2
  environment: 
    http_proxy: "{{ proxy }}"
    https_proxy: "{{ proxy }}"
  loop:
    - { name: 'enum4linux-ng', source: 'git+https://github.com/cddmp/enum4linux-ng' }
    - { name: 'waymore', source: 'git+https://github.com/xnl-h4ck3r/waymore' }
    - { name: 'xnLinkFinder' , source: 'git+https://github.com/xnl-h4ck3r/xnLinkFinder.git' }
    - { name: 'ghauri',source: 'git+https://github.com/r0oth3x49/ghauri'}
    - { name: 'Interlace',source: 'git+https://github.com/codingo/Interlace'}
    - { name: 'cloud_enum',source: 'git+https://github.com/initstring/cloud_enum'}
