#SPDX-License-Identifier: MIT-0
---
# handlers file for roles/configure-system
- name: Reload NetworkManager
  ansible.builtin.service:
    name: NetworkManager
    state: reloaded
  become: true
  become_method: ansible.builtin.sudo