general.live_config_reload = true

[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"

[font]
size = 18
normal.family = "FiraCode"
normal.style = "Regular"
bold.family = "FiraCode"
bold.style = "Bold"
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0

[window]
decorations = "Full"
dynamic_title = true
startup_mode = "Maximized"
dimensions.lines = 24
dimensions.columns = 96
padding.x = 4
padding.y = 2
opacity = 0.8

[bell]
animation = "EaseOutExpo"
duration = 0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"


[colors]
draw_bold_text_with_bright_colors = true
primary.background = "#1a1b20"
primary.foreground = "#cfd3e0"
#primary.foreground = "#bbc2de"

#[[colors.indexed_colors]]
#color = "0xF8BD96"
#index = 16

#[[colors.indexed_colors]]
#color = "0xF5E0DC"
#index = 17

#[colors.normal]
#black = "#6E6C7E"
##blue = "#96CDFB"
#blue = "#89aef3"
#cyan = "#89DCEB"
#green = "#ABE9B3"
#magenta = "#F5C2E7"
#red = "#F28FAD"
#white = "#D9E0EE"
#yellow = "#FAE3B0"

[colors.normal]
black = "#9399b2"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
yellow = "#f9e2af"
white = "#D9E0EE"


#[colors.bright]
#black = "#988BA2"
##blue = "#96CDFB"
#blue = "#89aef3"
#cyan = "#89DCEB"
#green = "#ABE9B3"
#magenta = "#F5C2E7"
#red = "#F28FAD"
#white = "#D9E0EE"
#yellow = "#FAE3B0"

[colors.bright]
black = "#9399b2"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
red = "#f38ba8"
yellow = "#f9e2af"
white = "#D9E0EE"


#[colors.cursor]
#cursor = "0xF5E0DC"
#text = "0x1E1D2F"

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false
style.blinking = "Off"
style.shape = "Block"

