export PATH=/usr/bin:/usr/local/bin:$HOME/.local/bin:$PATH

# store zinit and plugins path
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit"

# if Zinit Not exists, Download it
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Zinit Plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

# Snippet Plugins
zinit snippet OMZP::command-not-found

# Autoload zsh-completions
autoload -U compinit && compinit
# New zsh inherits current directory
zinit cdreplay -q
# Customized zsh-syntax-highlighting
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red'
ZSH_HIGHLIGHT_STYLES[path]='fg=blue'


# Allow "#comments" in interactive shell
setopt INTERACTIVE_COMMENTS
# Avoid pasting command Auto execution
#autoload -Uz bracketed-paste-magic

# History Setting
HISTSIZE=6000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
# All zsh share the same command history
setopt sharehistory
# Ignore begin with a space command and do not save its to the history
setopt hist_ignore_space
# Prevent duplicate commands in history
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
# Prevent duplicate commands historical search
setopt hist_find_no_dups


# Keybindings
# Emacs style
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[[3~' delete-char          # delete
bindkey '^[[3;5~' kill-word          # ctrl + delete
bindkey '^[[1;5C' forward-word       # ctrl + ->
bindkey '^[[1;5D' backward-word      # ctrl + <-
bindkey '^[[5~' beginning-of-buffer-or-history     # page up
bindkey '^[[6~' end-of-buffer-or-history           # page down

# Completion styling
# Ignore case
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
# Color Complement
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
# Disable default completion menu
zstyle ':completion:*' menu no
# Cd directory preview (fzf & fzf-tab)
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# Aliases
# Sudo inheriting PATH
alias sudo='sudo env PATH=$PATH'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -lh --group-directories-first'
alias la='ls -A --group-directories-first'
alias l='ls -CF --group-directories-first'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
alias cl='clear'
alias vim='nvim'
alias vi='nvim'
alias android-studio='/opt/android-studio/bin/studio.sh'


# Custom function
cd(){
  builtin cd "$@" && ls
}

# PATH
export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
export PATH=$PATH:$JAVA_HOME/bin

export PATH=$PATH:/snap/bin
export PATH=$PATH:$HOME/.cargo/bin

export GOROOT=/usr/lib/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export GOPROXY=https://goproxy.cn,direct

export NVM_DIR="$HOME/.config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Shell integrations
# fzf
eval "$(fzf --zsh)"
# brew
if [[ -f "/home/linuxbrew/.linuxbrew/bin/brew" ]]
then
  eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi
# oh-my-posh
eval "$(oh-my-posh init zsh --config $HOME/.config/ohmyposh/ohmyposh.toml)"

# Default terminator
TerminalEmulator=alacritty

export no_proxy=127.0.0.1,localhost
export https_proxy=http://192.168.10.1:10800
export http_proxy=http://192.168.10.1:10800
export all_proxy=socks5://192.168.10.1:10800
