---
- name: Add sudo NOPASSWD rules for the current user
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    insertbefore: EOF
    regexp: "{{ ansible_user_id }} ALL="
    line: "{{ item }}"
    validate: visudo -cf %s
    state: present
  become: true
  when: ansible_user_id != 'root'
  loop:
    - "{{ ansible_user_id }}\tALL=(ALL) NOPASSWD:ALL"